version: "3.7"

services:

  tor:
    container_name: tor
    image: tor
    build:
      context: ./docker/tor
      args:
        - TOR_VERSION=0.4.1.6
    volumes:
      - tor-data:/var/lib/tor
    restart: unless-stopped

  rkn-bypasser:
    container_name: rkn-bypasser
    image: rkn-bypasser
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    depends_on:
      - tor

volumes:
  tor-data: