version: "3.4"

services:

  tor:
    container_name: tor
    image: tor
    build: ./docker/tor
    volumes:
      - tor-data:/var/lib/tor
    restart: always

  rkn-bypasser:
    container_name: rkn-bypasser
    image: rkn-bypasser
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    depends_on:
      - tor

volumes:
  tor-data: