version: "3"
services:
  rkn-bypasser:
    build: ./
    ports:
      - 127.0.1.1:8000:8000
    restart: always
    depends_on:
      - tor
    environment:
      - TOR=tor:9150
  tor:
    build: ./tor
    ports:
      - 127.0.1.1:8001:9150